[phases.setup]
nixpkgs = ["nodejs", "python311", "pip"]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "npm install --prefix fantasy-basketball-frontend",
  "npm run build --prefix fantasy-basketball-frontend"
]

[start]
cmd = "python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000"